services:
  api:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - ASPNETCORE_ENVIRONMENT=Production

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: emp_program
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432